from enum import Enum


class RegistryErrorCodes(str, Enum):
    INVALID_REQUEST = "INVALID_REQUEST"
    REGISTRY_NOT_FOUND = "NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    DB_ERROR = "DB_ERROR"
